"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SoftChatProvider } from "softchatjs-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Title</title>
        <meta name="description" content="Description" />
      </head>
      <SoftChatProvider
        config={{
          userId: "20",
          username: "Tolu",
          apiKey: "1234",
          projectId: "5909b61d-e6be-47b5-bb54-a60e56344580",
        }}
      >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <>{children}</>
        </body>
      </SoftChatProvider>
    </html>
  );
}
