"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SoftChatProvider } from "softchatjs-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Title</title>
        <meta name="description" content="Description" />
      </head>
      <SoftChatProvider
        config={{
          userId: "20",
          username: "Tolu",
          subId: "ef066542-6e13-4f25-a6c3-d3e3671e4662",
          projectId: "5909b61d-e6be-47b5-bb54-a60e56344580",
          // theme: {
          //   background: {
          //     primary: "white",
          //     secondary: "white",
          //   },
          //   // text:"black",
          //   icon: "black",
          //   chatBubble: {
          //     left: {
          //       bgColor: "#F7F7F7",
          //       messageColor: "black",
          //       messageTimeColor: "black",
          //     },
          //     right: {
          //       bgColor: "#14D39D",
          //       messageColor: "black",
          //       messageTimeColor: "black",
          //     },
          //   },
          //   divider: "grey",
          //   text: {
          //     primary: "black",
          //   },
          //   hideDivider: true,
          //   input: {
          //     bgColor: "#F2F2F2",
          //     textColor: "black",
          //     emojiPickerTheme: "light",
          //   },
          // },
        }}
      >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <>{children}</>
        </body>
      </SoftChatProvider>
    </html>
  );
}
